version: '3'

services:
  nginx:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./../../www:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites/:/etc/nginx/sites-available
      - ./conf/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.web.rule=Host(`web.local`, `edoo.local`)"
          - "traefik.docker.network=traefik"
    networks:
      - traefik

  php:
    image: php8.1-edookit-fpm
    volumes:
      - ./../../www:/var/www/html
    networks:
      - traefik

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./pgsql/13/data/:/var/lib/postgresql/data
#      - ./../pgsql/13/data/:/var/lib/postgresql/data
    networks:
      - traefik
    ports:
      - '5432:5432'

networks:
  traefik:
    external: true

volumes:
  pgdata:
