version: '3'

services:
  traefik:
    image: traefik:v2.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
    ports:
      - '80:80'
      - '8080:8080'
    networks:
      - traefik
  nginx:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./../../www:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites/:/etc/nginx/sites-available
      - ./conf/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.web.rule=Host(`web.local`, `edoo.local`, `portal.edoo.local`, `api.edoo.local`)"
          - "traefik.docker.network=traefik"
    networks:
      - traefik

  php:
    build:
      dockerfile: php/8.1/Dockerfile.fpm
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php8.1-fpm-global
    volumes:
      - ./../../www:/var/www/html
    networks:
      - traefik

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./pgsql/13/data/:/var/lib/postgresql/data
#      - ./../pgsql/13/data/:/var/lib/postgresql/data
    networks:
      - traefik
    ports:
      - '5432:5432'

networks:
  traefik:
    external: true

volumes:
  pgdata:
