version: '3'

services:
  traefik:
    image: traefik:v2.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
    ports:
      - '80:80'
      - '8080:8080'
    networks:
      - traefik
  nginx:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./../../www:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites/:/etc/nginx/sites-available
      - ./conf/conf.d:/etc/nginx/conf.d
    depends_on:
      - php81-fpm
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nginx.rule=HostRegexp(`{domain:[a-z]+}.local`, `{subdomain:[a-z]+}.{domain:[a-z]+}.local`)"
    networks:
      - traefik

  php81-fpm:
    build:
      dockerfile: php/8.1/Dockerfile.fpm
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USERNAME=${USERNAME:-developer}
    volumes:
      - ./../../www:/var/www/html
      - ./php/8.1/conf/00-debug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - traefik
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file: .env

  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - ./pgsql/13/data/:/var/lib/postgresql/data
#      - ./../pgsql/13/data/:/var/lib/postgresql/data
    networks:
      - traefik
    ports:
      - '5432:5432'

networks:
  traefik:
    external: true

volumes:
  pgdata:
