## traefik.yml

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.project" }}.local`)'

entryPoints:
  http:
    address: ":80"
# API and dashboard configuration
api:
  dashboard: true
  insecure: true

