## traefik.yml

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

entryPoints:
  http:
    address: ":80"
# API and dashboard configuration
api:
  dashboard: true
  insecure: true

